### ISSUE TITLE
$page is null

### ISSUE THREAD

**Issue by tristantbg** [sylvainjule/kirby-autofocus#6]
Problem with fetching the page in api.php

<img width="447" alt="capture d ecran 2018-12-07 a 14 27 04" src="https://user-images.githubusercontent.com/4832038/49650387-51a3e280-fa2c-11e8-850f-3e0a2ab595e9.png">
<img width="642" alt="capture d ecran 2018-12-07 a 14 27 15" src="https://user-images.githubusercontent.com/4832038/49650388-51a3e280-fa2c-11e8-8c92-d0db5b3ca51b.png">

**Comment by sylvainjule** [comment]
Let me know if the last commit fixes this! It should.

**Comment by tristantbg** [comment]
Thank you! Works perfectly now.

(I tried to do page($uri) but didn't know you needed to add kirby() before in plugins)

**Comment by sylvainjule** [comment]
The issue was also with the uri formatting, the panel is now sending a `pages/projects+moving-images+the-last-souvenir` string, while it must be `projects/moving-images/the-last-souvenir` to be used as the `page()` method argument.

(I didn't even try it without `kirby()` actually, just tried also and indeed it's needed. The shortcut is probably wrapping `$kirby->page()`, while `$kirby` isn't defined in plugins).
